import type { Deal } from '../page';

// Assuming Deal type is exported or accessible

export const mockDeals: Deal[] = [
  {
    id: 'mock-1',
    companyName: 'Innovatech Solutions',
    industry: 'AI & Machine Learning',
    value: '$75,000',
    contact: 'Alice Wonderland',
    email: 'alice@innovatech.com',
    stage: 'interested',
    createdAt: '3d ago',
    companySize: '50-100 employees',
    website: 'www.innovatech.com',
    dealTitle: 'AI Chatbot Integration',
    nextAction: 'Schedule initial demo call',
    probability: 20,
    closeDate: '2025-08-15',
    painPoints: ['High customer support volume', 'Slow response times'],
    nextSteps: ['Send introductory email', 'Research company further'],
    momentum: 30,
    momentumTrend: 'steady',
    momentumMarkers: [
      {
        type: 'buying_question',
        timestamp: '1d ago',
        description: 'Asked about pricing tiers',
        impact: 'medium',
      },
    ],
  },
  {
    id: 'mock-2',
    companyName: 'GreenLeaf Organics',
    industry: 'Sustainable Agriculture',
    value: '$50,000',
    contact: 'Bob The Builder',
    email: 'bob@greenleaf.com',
    stage: 'qualified',
    createdAt: '1w ago',
    companySize: '20-50 employees',
    website: 'www.greenleaf.com',
    dealTitle: 'Organic Supply Chain Software',
    nextAction: 'Send proposal document',
    probability: 40,
    closeDate: '2025-07-30',
    painPoints: [
      'Inefficient inventory tracking',
      'Lack of supplier transparency',
    ],
    nextSteps: ['Finalize proposal details', 'Discuss implementation timeline'],
    momentum: 60,
    momentumTrend: 'accelerating',
    momentumMarkers: [
      {
        type: 'stakeholder_intro',
        timestamp: '2d ago',
        description: 'Introduced to Head of Operations',
        impact: 'high',
      },
      {
        type: 'prospect_next_step',
        timestamp: '1d ago',
        description: 'Requested detailed feature list',
        impact: 'medium',
      },
    ],
  },
  {
    id: 'mock-3',
    companyName: 'CyberSecure Ltd.',
    industry: 'Cybersecurity',
    value: '$120,000',
    contact: 'Carol Danvers',
    email: 'carol@cybersecure.com',
    stage: 'demo',
    createdAt: '2d ago',
    companySize: '100-200 employees',
    website: 'www.cybersecure.com',
    dealTitle: 'Advanced Threat Detection Platform',
    nextAction: 'Follow up after demo',
    probability: 60,
    closeDate: '2025-07-20',
    painPoints: ['Recent security incidents', 'Outdated security software'],
    nextSteps: [
      'Address technical questions from demo',
      'Schedule follow-up with CISO',
    ],
    last_meeting_summary:
      'Demo went well, showed strong interest in threat detection capabilities',
    momentum: 75,
    momentumTrend: 'accelerating',
    momentumMarkers: [
      {
        type: 'buying_question',
        timestamp: 'Today',
        description: 'Inquired about integration with existing SIEM',
        impact: 'high',
      },
    ],
  },
  {
    id: 'mock-4',
    companyName: 'FinTech Innovators',
    industry: 'Financial Technology',
    value: '$90,000',
    contact: 'David Copperfield',
    email: 'david@fintechinnov.com',
    stage: 'proposal',
    createdAt: '5h ago',
    companySize: '50-100 employees',
    website: 'www.fintechinnov.com',
    dealTitle: 'Blockchain Payment Solution',
    nextAction: 'Review proposal feedback',
    probability: 75,
    closeDate: '2025-07-10',
    painPoints: ['High transaction fees', 'Slow international payments'],
    nextSteps: ['Negotiate contract terms', 'Finalize service level agreement'],
    last_meeting_summary:
      'Proposal presentation successful, CFO expressed strong interest',
    momentum: 85,
    momentumTrend: 'accelerating',
    momentumMarkers: [
      {
        type: 'prospect_next_step',
        timestamp: '1h ago',
        description: 'Confirmed proposal received, internal review scheduled',
        impact: 'high',
      },
    ],
  },
  {
    id: 'mock-5',
    companyName: 'HealthWell Clinic',
    industry: 'Healthcare',
    value: '$65,000',
    contact: 'Eve Adams',
    email: 'eve@healthwell.com',
    stage: 'interested',
    createdAt: '4d ago',
    companySize: '30-70 employees',
    website: 'www.healthwell.com',
    dealTitle: 'Patient Management System',
    nextAction: 'Send case studies',
    probability: 25,
    closeDate: '2025-09-01',
    painPoints: [
      'Manual appointment scheduling',
      'Disorganized patient records',
    ],
    nextSteps: [
      'Identify key decision-makers',
      'Tailor presentation to clinic needs',
    ],
    momentum: 20,
    momentumTrend: 'steady',
    momentumMarkers: [],
  },
  {
    id: 'mock-6',
    companyName: 'EduGrowth Platforms',
    industry: 'EdTech',
    value: '$40,000',
    contact: 'Frank N. Stein',
    email: 'frank@edugrowth.com',
    stage: 'qualified',
    createdAt: '2w ago',
    companySize: '10-30 employees',
    website: 'www.edugrowth.com',
    dealTitle: 'Online Learning Module Creator',
    nextAction: 'Prepare for demo',
    probability: 35,
    closeDate: '2025-08-25',
    painPoints: ['Low student engagement', 'Difficult content creation tools'],
    nextSteps: [
      'Customize demo for their curriculum',
      'Highlight engagement features',
    ],
    momentum: 45,
    momentumTrend: 'steady',
    momentumMarkers: [
      {
        type: 'buying_question',
        timestamp: '3d ago',
        description: 'Asked about SCORM compatibility',
        impact: 'medium',
      },
    ],
  },
  {
    id: 'mock-7',
    companyName: 'RetailRevolution',
    industry: 'E-commerce',
    value: '$110,000',
    contact: 'Grace Hopper',
    email: 'grace@retailrev.com',
    stage: 'demo',
    createdAt: '6d ago',
    companySize: '200-500 employees',
    website: 'www.retailrev.com',
    dealTitle: 'Personalized Recommendation Engine',
    nextAction: 'Send demo recording and summary',
    probability: 55,
    closeDate: '2025-08-05',
    painPoints: ['Low conversion rates', 'Generic user experience'],
    nextSteps: ['Gather feedback on demo', 'Discuss A/B testing possibilities'],
    momentum: 65,
    momentumTrend: 'accelerating',
    momentumMarkers: [
      {
        type: 'prospect_next_step',
        timestamp: '1d ago',
        description: 'Requested access to a sandbox environment',
        impact: 'high',
      },
    ],
  },
  {
    id: 'mock-8',
    companyName: 'LogisticsLink',
    industry: 'Supply Chain & Logistics',
    value: '$80,000',
    contact: 'Henry Ford',
    email: 'henry@logisticslink.com',
    stage: 'interested',
    createdAt: '1d ago',
    companySize: '70-150 employees',
    website: 'www.logisticslink.com',
    dealTitle: 'Real-time Fleet Tracking',
    nextAction: 'Initial contact call',
    probability: 15,
    closeDate: '2025-09-10',
    painPoints: ['Lack of visibility into shipments', 'High fuel costs'],
    nextSteps: [
      'Understand current tracking methods',
      'Explain ROI of real-time data',
    ],
    momentum: 10,
    momentumTrend: 'steady',
    momentumMarkers: [],
  },
  {
    id: 'mock-9',
    companyName: 'MediaMakers Inc.',
    industry: 'Digital Media',
    value: '$55,000',
    contact: 'Ivy Lee',
    email: 'ivy@mediamakers.com',
    stage: 'qualified',
    createdAt: '10d ago',
    companySize: '40-80 employees',
    website: 'www.mediamakers.com',
    dealTitle: 'Content Management System Upgrade',
    nextAction: 'Schedule technical deep-dive',
    probability: 45,
    closeDate: '2025-08-20',
    painPoints: [
      'Slow website performance',
      'Difficult content update process',
    ],
    nextSteps: ['Assess current CMS limitations', 'Showcase migration ease'],
    momentum: 50,
    momentumTrend: 'steady',
    momentumMarkers: [
      {
        type: 'stakeholder_intro',
        timestamp: '4d ago',
        description: 'Met with their Head of Content',
        impact: 'medium',
      },
    ],
  },
  {
    id: 'mock-10',
    companyName: 'TravelWise Agency',
    industry: 'Travel & Tourism',
    value: '$30,000',
    contact: 'Jack Sparrow',
    email: 'jack@travelwise.com',
    stage: 'interested',
    createdAt: 'Just now',
    companySize: '5-15 employees',
    website: 'www.travelwise.com',
    dealTitle: 'Booking Engine Optimization',
    nextAction: 'Send introductory package',
    probability: 10,
    closeDate: '2025-09-15',
    painPoints: ['Low online booking rates', 'Complex booking process'],
    nextSteps: [
      'Analyze current booking funnel',
      'Highlight conversion improvements',
    ],
    momentum: 5,
    momentumTrend: 'steady',
    momentumMarkers: [],
  },
];
